In [18]:
import torch
import torch.nn.functional as F

def test_attention():
    batch_size, q_seq_len, embed_dim, heads = 2, 10, 8, 2
    k_seq_len = 10
    
    query = torch.randn(batch_size, heads, q_seq_len, embed_dim)
    key = torch.randn(batch_size, heads, k_seq_len, embed_dim)
    value = torch.randn(batch_size, heads, k_seq_len, embed_dim)
    
    # Test without mask
    x_no_mask = F.scaled_dot_product_attention(query, key, value, attn_mask=None, dropout_p=0.0, is_causal=False)
    # print("Output without mask:\n", x_no_mask)
    
    # Test with mask
        # Test with mask
    mask = torch.zeros(batch_size, q_seq_len, dtype=torch.bool)
    for i in range(batch_size):
        rand_idx = torch.randint(q_seq_len-10, q_seq_len, (1,)).item()
        print("Random index:", rand_idx)
        mask[i, rand_idx:] = True
    print("\nMask:\n", mask)
    #my mask
    attn_mask = mask.unsqueeze(2) | mask.unsqueeze(1)  # [B, T1, T2]
    attn_mask = attn_mask.unsqueeze(1).expand(-1, heads, -1, -1)  # [B, n_head, T1, T2]
    attn_mask = ~attn_mask
    print("\nAttn Mask:\n", attn_mask)
    # attn_mask = attn_mask.permute(1, 0, 2, 3).contiguous().view(-1, q_seq_len, k_seq_len) 

    # in paper
    # attn_mask = mask.unsqueeze(1).unsqueeze(1)  # 'b n -> b 1 1 n'
    # attn_mask = attn_mask.expand(batch_size, heads, q_seq_len, k_seq_len)
    
    x_with_mask = F.scaled_dot_product_attention(query, key, value, attn_mask=attn_mask, dropout_p=0.0, is_causal=False)
    print("\nOutput with mask:\n", x_with_mask)

if __name__ == "__main__":
    test_attention()


Random index: 6
Random index: 2

Mask:
 tensor([[False, False, False, False, False, False,  True,  True,  True,  True],
        [False, False,  True,  True,  True,  True,  True,  True,  True,  True]])

Attn Mask:
 tensor([[[[ True,  True,  True,  True,  True,  True, False, False, False, False],
          [ True,  True,  True,  True,  True,  True, False, False, False, False],
          [ True,  True,  True,  True,  True,  True, False, False, False, False],
          [ True,  True,  True,  True,  True,  True, False, False, False, False],
          [ True,  True,  True,  True,  True,  True, False, False, False, False],
          [ True,  True,  True,  True,  True,  True, False, False, False, False],
          [False, False, False, False, False, False, False, False, False, False],
          [False, False, False, False, False, False, False, False, False, False],
          [False, False, False, False, False, False, False, False, False, False],
          [False, False, False, False, False, Fa

In [20]:
    k_seq_len = 10
    
    query = torch.randn(batch_size, heads, q_seq_len, embed_dim)
    key = torch.randn(batch_size, heads, k_seq_len, embed_dim)
    value = torch.randn(batch_size, heads, k_seq_len, embed_dim)
    
    # Test without mask
    x_no_mask = F.scaled_dot_product_attention(query, key, value, attn_mask=None, dropout_p=0.0, is_causal=False)
    # print("Output without mask:\n", x_no_mask)
    
    # Test with mask
        # Test with mask
    mask = torch.zeros(batch_size, q_seq_len, dtype=torch.bool)
    for i in range(batch_size):
        rand_idx = torch.randint(q_seq_len-10, q_seq_len, (1,)).item()
        print("Random index:", rand_idx)
        mask[i, rand_idx:] = True
    print("\nMask:\n", mask)
    #my mask
    attn_mask = mask.unsqueeze(2) | mask.unsqueeze(1)  # [B, T1, T2]
    attn_mask = attn_mask.unsqueeze(1).expand(-1, heads, -1, -1)  # [B, n_head, T1, T2]
    attn_mask = ~attn_mask
    print("\nAttn Mask:\n", attn_mask)
    # attn_mask = attn_mask.permute(1, 0, 2, 3).contiguous().view(-1, q_seq_len, k_seq_len) 

    # in paper
    # attn_mask = mask.unsqueeze(1).unsqueeze(1)  # 'b n -> b 1 1 n'
    # attn_mask = attn_mask.expand(batch_size, heads, q_seq_len, k_seq_len)
    
    x_with_mask = F.scaled_dot_product_attention(query, key, value, attn_mask=attn_mask, dropout_p=0.0, is_causal=False)
    print("\nOutput with mask:\n", x_with_mask)

Random index: 5
Random index: 7

Mask:
 tensor([[False, False, False, False, False,  True,  True,  True,  True,  True],
        [False, False, False, False, False, False, False,  True,  True,  True]])

Attn Mask:
 tensor([[[[ True,  True,  True,  True,  True, False, False, False, False, False],
          [ True,  True,  True,  True,  True, False, False, False, False, False],
          [ True,  True,  True,  True,  True, False, False, False, False, False],
          [ True,  True,  True,  True,  True, False, False, False, False, False],
          [ True,  True,  True,  True,  True, False, False, False, False, False],
          [False, False, False, False, False, False, False, False, False, False],
          [False, False, False, False, False, False, False, False, False, False],
          [False, False, False, False, False, False, False, False, False, False],
          [False, False, False, False, False, False, False, False, False, False],
          [False, False, False, False, False, Fa

In [21]:
x_with_mask

tensor([[[[-0.1269, -0.1954, -0.3799,  0.4779, -0.2285,  0.5627, -0.0790,
           -1.1848],
          [-0.1795, -0.1105, -0.0083,  0.6442,  0.0469,  0.4419, -0.4440,
           -0.9870],
          [-0.3094, -0.1114, -0.3263,  0.8099,  0.6350,  0.0862, -0.7396,
           -1.8031],
          [-0.6503, -0.6527, -0.4128,  0.5423, -0.0277,  0.5948,  0.4520,
           -0.9407],
          [-0.3243, -0.1910, -0.4199,  0.7337,  0.1346,  0.2707, -0.0239,
           -1.3424],
          [    nan,     nan,     nan,     nan,     nan,     nan,     nan,
               nan],
          [    nan,     nan,     nan,     nan,     nan,     nan,     nan,
               nan],
          [    nan,     nan,     nan,     nan,     nan,     nan,     nan,
               nan],
          [    nan,     nan,     nan,     nan,     nan,     nan,     nan,
               nan],
          [    nan,     nan,     nan,     nan,     nan,     nan,     nan,
               nan]],

         [[ 0.1056, -0.1477,  0.4569,  0.3805, -

In [ ]:
x_with_mask

In [10]:
attn_mask = mask.unsqueeze(2) | mask.unsqueeze(1)  # [B, T1, T2]
attn_mask = attn_mask.unsqueeze(1).expand(-1, heads, -1, -1)  # [B, n_head, T1, T2]
attn_mask = attn_mask.permute(1, 0, 2, 3).contiguous().view(-1, q_seq_len, k_seq_len) 
attn_mask

tensor([[[False, False, False, False, False, False, False,  True,  True,  True],
         [False, False, False, False, False, False, False,  True,  True,  True],
         [False, False, False, False, False, False, False,  True,  True,  True],
         [False, False, False, False, False, False, False,  True,  True,  True],
         [False, False, False, False, False, False, False,  True,  True,  True],
         [False, False, False, False, False, False, False,  True,  True,  True],
         [False, False, False, False, False, False, False,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  T

In [12]:
    attn_mask = mask.unsqueeze(1).unsqueeze(1)  # 'b n -> b 1 1 n'
    attn_mask = attn_mask.expand(batch_size, heads, q_seq_len, k_seq_len)

In [14]:
attn_mask.shape

torch.Size([2, 2, 10, 10])